---
- name: Installing docker for centos
  hosts: centos
  roles:
    - centos-docker
    - centos-groupd

- name: Installing docker for ubuntu
  hosts: ubuntu
  roles:
    - ubuntu-docker
    - ubuntu-userd
    - ubuntu-webdb
